import { type Category } from '@/lib/nlp/schema';

const domainCategories = [
  {
    code: 'R',
    category: 'religion',
    vietnamese: 'Tôn giáo',
    categoryType: 'domain',
  },
] as const satisfies Category[];

const subDomainCategories = [
  {
    code: 'C',
    category: 'catholic',
    vietnamese: 'Công giáo',
    categoryType: 'subDomain',
  },
] as const satisfies Category[];

const genreCategories = [
  {
    code: 'A',
    category: '',
    vietnamese: '',
    categoryType: 'genre',
    isReserved: true,
  },
  {
    code: 'B',
    category: '',
    vietnamese: '',
    categoryType: 'genre',
    isReserved: true,
  },
  {
    code: 'C',
    category: 'catechesis',
    vietnamese: 'Giáo lý/Giáo huấn',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'D',
    category: 'church document',
    vietnamese: 'Văn kiện Giáo Hội',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'E',
    category: 'exegesis/commentary',
    vietnamese: 'Chú giải/Bình luận',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'F',
    category: '',
    vietnamese: '',
    categoryType: 'genre',
    isReserved: true,
  },
  {
    code: 'G',
    category: '',
    vietnamese: '',
    categoryType: 'genre',
    isReserved: true,
  },
  {
    code: 'H',
    category: '',
    vietnamese: '',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'I',
    category: 'contemplation',
    vietnamese: 'Suy niệm',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'J',
    category: 'gospel contemplation',
    vietnamese: 'Suy niệm Lời Chúa',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'K',
    category: '',
    vietnamese: '',
    categoryType: 'genre',
    isReserved: true,
  },
  {
    code: 'L',
    category: 'liturgical',
    vietnamese: 'Phụng vụ',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'M',
    category: 'memoir',
    vietnamese: 'Hồi ký',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'N',
    category: 'new testament',
    vietnamese: 'Kinh Thánh Tân Ước',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'O',
    category: 'old testament',
    vietnamese: 'Kinh Thánh Cựu Ước',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'P',
    category: 'prayer',
    vietnamese: 'Cầu nguyện',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'Q',
    category: '',
    vietnamese: '',
    categoryType: 'genre',
    isReserved: true,
  },
  {
    code: 'R',
    category: '',
    vietnamese: '',
    categoryType: 'genre',
    isReserved: true,
  },
  {
    code: 'S',
    category: 'saint/beatification biography',
    vietnamese: 'Tiểu sử Thánh/Chân phước',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'T',
    category: 'theology',
    vietnamese: 'Thần học',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'U',
    category: '',
    vietnamese: '',
    categoryType: 'genre',
    isReserved: true,
  },
  {
    code: 'V',
    category: '',
    vietnamese: '',
    categoryType: 'genre',
    isReserved: true,
  },
  {
    code: 'W',
    category: '',
    vietnamese: '',
    categoryType: 'genre',
    isReserved: true,
  },
  {
    code: 'X',
    category: '',
    vietnamese: '',
    categoryType: 'genre',
    isReserved: true,
  },
  {
    code: 'Y',
    category: 'philosophy',
    vietnamese: 'Triết học',
    categoryType: 'genre',
    isReserved: false,
  },
  {
    code: 'Z',
    category: 'others',
    vietnamese: 'Khác',
    categoryType: 'genre',
    isReserved: false,
  },
] as const satisfies Category[];

const tagCategories = [
  {
    code: '',
    category: 'apostolic constitution',
    vietnamese: 'Tông hiến (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'encyclical letter',
    vietnamese: 'Thông điệp (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'apostolic letter',
    vietnamese: 'Tông thư (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'declarations',
    vietnamese: 'Tuyên ngôn (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'motu proprio',
    vietnamese: 'Tài liệu dưới dạng tự sắc (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'apostolic exhortations',
    vietnamese: 'Tông huấn (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'note document',
    vietnamese: 'Ghi chú (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'urbi et orbi message',
    vietnamese: 'Sứ điệp Giáng Sinh/Phục Sinh (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'constitution',
    vietnamese: 'Hiến chế (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'decrees',
    vietnamese: 'Sắc lệnh (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'instrumentum laboris',
    vietnamese: 'Tài liệu làm việc (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'synod of bishops note',
    vietnamese: 'Ghi chú của Thượng Hội đồng Giám mục (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'letters',
    vietnamese: 'Thư (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'messages',
    vietnamese: 'Sứ điệp (Văn kiện Giáo Hội)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'bible pentateuch division',
    vietnamese: 'Ngũ Thư (Kinh Thánh Cựu Ước)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'bible historical books division',
    vietnamese: 'Lịch Sử (Kinh Thánh Cựu Ước)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'bible poetic/wisdom books division',
    vietnamese: 'Giáo huấn - Khôn ngoan (Kinh Thánh Cựu Ước)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'bible prophetic books division',
    vietnamese: 'Ngôn sứ - Tiên tri (Kinh Thánh Cựu Ước)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'bible gospels division',
    vietnamese: 'Sách Phúc Âm - Tin Mừng (Kinh Thánh Tân Ước)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'bible acts division',
    vietnamese: 'Sách Công vụ Tông đồ (Kinh Thánh Tân Ước)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'bible pauline letters division',
    vietnamese: 'Các thư mục vụ của Thánh Phao-lô (Kinh Thánh Tân Ước)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'bible general epistles division',
    vietnamese: 'Các thư chung (Kinh Thánh Tân Ước)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'bible revelation division',
    vietnamese: 'Sách Khải Huyền (Kinh Thánh Tân Ước)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'morning and evening prayers',
    vietnamese: 'Các kinh đọc sáng tối ngày thường và Chúa Nhật (Cầu nguyện)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category:
      'offertory prayer, prayers of preparation for holy communion and prayers of thanksgiving',
    vietnamese:
      'Kinh dâng lễ, những kinh dọn mình chịu lễ và những kinh cám ơn (Cầu nguyện)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'the stations of the cross prayers',
    vietnamese: 'Kinh ngắm Đàng Thánh giá và ít nhiều kinh khác (Cầu nguyện)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'rosary prayers',
    vietnamese: 'Phép lần hạt Mân Côi (Cầu nguyện)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'prayers',
    vietnamese: 'Kinh cầu (Cầu nguyện)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'daily prayers',
    vietnamese: 'Kinh đọc hàng ngày (Cầu nguyện)',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'maria',
    vietnamese: 'Mẹ Maria',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'advent',
    vietnamese: 'Mùa Vọng',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'christmas',
    vietnamese: 'Mùa Giáng Sinh',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'lent',
    vietnamese: 'Mùa Chay',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'triduum',
    vietnamese: 'Mùa Chay - Tuần Thánh',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'easter',
    vietnamese: 'Mùa Phục Sinh',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'ot',
    vietnamese: 'Mùa Thường niên',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'christmas',
    vietnamese: 'Mùa Giáng Sinh',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'celebrations',
    vietnamese: 'Lễ lớn',
    categoryType: 'tag',
    isReserved: false,
  },
  {
    code: '',
    category: 'jubilee year',
    vietnamese: 'Năm Thánh',
    categoryType: 'tag',
    isReserved: false,
  },
] as const satisfies Category[];

const languageCategories = [
  {
    code: 'V',
    category: 'vietnamese',
    vietnamese: 'Việt',
    categoryType: 'language',
    isReserved: false,
  },
  {
    code: 'C',
    category: 'chinese',
    vietnamese: 'Hán',
    categoryType: 'language',
    isReserved: false,
  },
] as const satisfies Category[];

export {
  domainCategories,
  subDomainCategories,
  genreCategories,
  tagCategories,
  languageCategories,
};
